import {
  LOAD_INITIATION_TYPE,
  LOAD_SUCCESS_TYPE,
  LOAD_FAILURE_TYPE,
  LOAD_CANCEL_TYPE,
  AUTHENTICATE_TYPE,
} from './types';

export const LOAD_INITIATION: LOAD_INITIATION_TYPE = 'SAMPLEAUTH/LOAD_INITIATION';
export const LOAD_SUCCESS: LOAD_SUCCESS_TYPE = 'SAMPLEAUTH/LOAD_SUCCESS';
export const LOAD_FAILURE: LOAD_FAILURE_TYPE = 'SAMPLEAUTH/LOAD_FAILURE';
export const LOAD_CANCEL: LOAD_CANCEL_TYPE = 'SAMPLEAUTH/LOAD_CANCEL';
export const AUTHENTICATE: AUTHENTICATE_TYPE = 'SAMPLEAUTH/AUTHENTICATE';
